name: "my Ruby workflow"

on: [push, pull_request]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: mscwilson/changelog-creator

      - name: Print ENV
        run: env

      - name: echo stuff
        run: echo $GITHUB_EVENT_NAME

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs ‘bundle install’ and caches installed gems automatically

      - name: Run ruby script
        if: ${{ env.GITHUB_EVENT_NAME }} == "pull_request" && github.event.action == "opened"
        uses: mscwilson/changelog-creator@main
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
