name: "Update issue labels"
on: [push, create]

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update issue labels
        uses: mscwilson/labels-helper-action@main
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
