name: "Update issue labels"
on:
  create:
  pull_request:
    types:
      - opened
  push:
    branches:
      - "release/**"

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update issue labels
        uses: snowplow-incubator/labels-helper-action@main
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
