name: "Match PR to issue"
on:
  push
  # pull_request:
  #   types:
  #     - opened
  #   branches:
  #     - "release/**"
  # push:
  #   branches:
  #     - "release/**"

jobs:
  sort-out-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Match the issue to the PR
        uses: mscwilson/pull-request-helper-action@main
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
