name: "Update status labels"

on:
  create:
  push:
  pull_request:
    types: [opened, merged]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true # runs ‘bundle install’ and caches installed gems automatically

      - name: Run ruby script
        uses: mscwilson/changelog-test/issue_labels@1.4
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pwd
